//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class emisor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emisor()
        {
            this.facturaElectronica = new HashSet<facturaElectronica>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Identificacion { get; set; }
        public string NombreComercial { get; set; }
        public int Ubicacion { get; set; }
        public int Telefono { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual identificacion identificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaElectronica> facturaElectronica { get; set; }
    }
}
