//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturaDigitalEntities1 : DbContext
    {
        public FacturaDigitalEntities1()
            : base("name=FacturaDigitalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<emisor> emisor { get; set; }
        public virtual DbSet<facturaElectronica> facturaElectronica { get; set; }
        public virtual DbSet<identificacion> identificacion { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<numeroLinea> numeroLinea { get; set; }
        public virtual DbSet<receptor> receptor { get; set; }
        public virtual DbSet<sucursales> sucursales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tipoDecimalDinero> tipoDecimalDinero { get; set; }
        public virtual DbSet<tipoDescuento> tipoDescuento { get; set; }
        public virtual DbSet<tipoDetalleServicio> tipoDetalleServicio { get; set; }
        public virtual DbSet<tipoIdentificacion> tipoIdentificacion { get; set; }
        public virtual DbSet<tipoImpuestos> tipoImpuestos { get; set; }
        public virtual DbSet<tipoMedioPago> tipoMedioPago { get; set; }
        public virtual DbSet<tipoSituacion> tipoSituacion { get; set; }
        public virtual DbSet<unidadDeMedida> unidadDeMedida { get; set; }
    }
}
