//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturaElectronica
    {
        public string Clave { get; set; }
        public string CodigoActividad { get; set; }
        public int NumeroConsecutivo { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int Emisor { get; set; }
        public int Receptor { get; set; }
        public string CondicionVenta { get; set; }
        public string PlazoCredito { get; set; }
        public string MedioPago { get; set; }
        public Nullable<int> DetalleServicio { get; set; }
        public Nullable<int> OtrosCargos { get; set; }
        public Nullable<int> ResumenFactura { get; set; }
        public Nullable<int> InformacionReferencia { get; set; }
        public Nullable<int> Otros { get; set; }
    
        public virtual emisor emisor1 { get; set; }
        public virtual receptor receptor1 { get; set; }
        public virtual tipoDetalleServicio tipoDetalleServicio { get; set; }
        public virtual tipoMedioPago tipoMedioPago { get; set; }
    }
}
