//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class numeroLinea
    {
        public int id { get; set; }
        public int Tiquete { get; set; }
        public int Codigo { get; set; }
        public Nullable<int> CodigoComercial { get; set; }
        public int Cantidad { get; set; }
        public int UnidadMedida { get; set; }
        public string UnidadMedidaComercial { get; set; }
        public string Detalle { get; set; }
        public int PrecioUnitario { get; set; }
        public int MontoTotal { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<int> SubTotal { get; set; }
        public Nullable<int> BaseImponible { get; set; }
        public Nullable<int> Impuesto { get; set; }
        public Nullable<int> ImpuestoNeto { get; set; }
    
        public virtual tipoDecimalDinero tipoDecimalDinero { get; set; }
        public virtual tipoDecimalDinero tipoDecimalDinero1 { get; set; }
        public virtual tipoDecimalDinero tipoDecimalDinero2 { get; set; }
        public virtual tipoDecimalDinero tipoDecimalDinero3 { get; set; }
        public virtual tipoDecimalDinero tipoDecimalDinero4 { get; set; }
        public virtual tipoDescuento tipoDescuento { get; set; }
        public virtual tipoDetalleServicio tipoDetalleServicio { get; set; }
        public virtual tipoImpuestos tipoImpuestos { get; set; }
        public virtual unidadDeMedida unidadDeMedida { get; set; }
    }
}
